baseURL = "https://adisen99.github.io/food4thought/"
languageCode = "en-us"
title = "Food 4 Thought"
theme = "mediumish"
summaryLength = 25
copyright = "Aditya Sengupta - All rights reserved"
enableEmoji = true
publishDir = "docs"
disqusShortname = "food-4-thought"
googleAnalytics = "UA-158627255-1"

[params]
  logo = "/images/favicon_io/favicon-32x32.png"
  description ="Physics, linux, programming, the Atmosphere and my life."
  #mailchimp = "you can provide a mailchimp-link here"

[params.author]
  name = "Aditya Sengupta"
  thumbnail = "/images/owl.jpg"
  description = "Creator of this blog."

[params.index]
  picture = "/images/owl.jpg"
  title = "Aditya Sengupta"
  subtitle = "A curious student studying about the Atmosphere."
  mdtext = '''
I love linux, programming and chess.\
**This website contains my personal blog and some of my project descriptions and what I am studying**\
### Hope you find something useful on the blog.
'''
  alertbar = true

[params.social]
  github = "adisen99"
  gitlab = "adisen99"
  linkedin = "aditya-sengupta-10"
  researchgate = "Aditya_Sengupta5"
  #xing = "<username>"
  #medium = "<username>"
  twitter = "adi_sen99"
  instagram = "adi_sen99"

## Main Menu
[[menu.main]]
    name = "Blog"
    weight = 100
    identifier = "blog"
    url = "/blog"
[[menu.main]]
    name = "About Me"
    identifier = "about"
    weight = 200
    url = "/static/about_me"
[[menu.main]]
    name = "Imprint"
    identifier = "imprint"
    weight = 300
    url = "/static/imprint"
