title = "Food for Thought"
baseURL = "https://adisen99.github.io/food4thought/"
languageCode = "en-us"
theme = "ananke"
publishDir = "docs"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 
enableRobotsTXT = true
disqusShortname = "food-for-thought-3"
googleAnalytics = "UA-158627255-1"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon.png"
  description = "Explore the Beauty of Scientific Thought and Wisdom."
  facebook = ""
  twitter = "https://twitter.com/adi_sen99"
  instagram = "https://www.instagram.com/adi_sen99/"
  youtube = ""
  github = "https://github.com/adisen99"
  gitlab = "https://gitlab.com/adisen99"
  linkedin = "https://www.linkedin.com/in/aditya-sengupta-10/"
  researchgate = "https://www.researchgate.net/profile/Aditya_Sengupta5"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/Physics.jpg"
  recent_posts_number = 3
  commentoEnable = false
  custom_css = ["/css/custom1.css"]
  custom_js = ["/js/custom1.js"]
